name: enkaperinaj
favicon: null
layout_spectrum: 0.03739
typography_spectrum: 0.29237
title: 'enka perinaj, holistic nutritionist & psychologist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1fbccc'
    - '#000000'
    - '#717155'
    - '#bfbfbf'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
